name: REACT CI

on:
  push:
    branches: [ main ]
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with react-scripts and report coverage
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
        
      - name: Install dependencies
        run: |
          npm install codecov -g
          npm install
          
      - name: Build
        run: |
          npm run build
      
      - name: Test
        run: npm run test -- --coverage

      - name: Upload coverage report
        run: codecov

      - name: 📦Pack
        run: npm pack

      - uses: actions/upload-artifact@v2
        with:
          name: npm-package
          path: configcat-react*.tgz
        
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aleixmorgadas'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: |
          npm run build

      - name: 🚀Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
